# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion






class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время игры')),
                ('fallen_count', models.IntegerField(verbose_name='Упавшие')),
                ('idle_count', models.IntegerField(verbose_name='Холостые')),
                ('prise', models.BooleanField(verbose_name='Приз')),
                ('interrupt', models.BooleanField(verbose_name='Прерывание')),
                ('service', models.IntegerField(verbose_name='Служебные')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Мишень',
                'verbose_name_plural': 'Мишени',
            },
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
        migrations.AlterModelOptions(
            name='tradepoint',
            options={'verbose_name': 'Торговая точка', 'verbose_name_plural': 'Тороговые точки'},
        ),
        migrations.RemoveField(
            model_name='tradepoint',
            name='game_count',
        ),
        migrations.RemoveField(
            model_name='tradepoint',
            name='target_count',
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='address',
            field=models.CharField(max_length=600, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='close_time',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='open_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='region',
            field=models.CharField(max_length=200, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='target',
            name='trade_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TradePoint'),
        ),
        migrations.AddField(
            model_name='game',
            name='trade_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.TradePoint'),
        ),
    ]
