# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_create_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepoint',
            name='target_count',
            field=models.IntegerField(default=1, verbose_name='Количество мишеней'),
        ),
        migrations.AlterField(
            model_name='game',
            name='target',
            field=models.IntegerField(verbose_name='Мишень'),
        ),
    ]
