# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20170429_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='end_time',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Конец работы'),
        ),
        migrations.AddField(
            model_name='operator',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Начало работы'),
        ),
        migrations.AddField(
            model_name='operator',
            name='trade_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.TradePoint'),
            preserve_default=False,
        ),
    ]
