# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20170429_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='phone',
            field=models.CharField(default=1, max_length=200, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
