# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20170429_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepoint',
            name='label',
            field=models.IntegerField(default=1, verbose_name='ID'),
        ),
    ]
